georgia-tech-db/evadb

.gitignore
environment_mac.yml
loaders/color_detection.py
loaders/load.py

Modified gitignore and environment creation file for mac.

Minor changes

---

.githooks/linker.sh
.githooks/pre-commit
.githooks/pre-commit.d/01-formatter
.githooks/pre-commit.d/02-check-binary
.travis.yml
README.md
script/linker.sh
src/demo.py
src/parser/insert_statement.py

Added githooks support. Scripts formatter.py, validator.py work now after every commit. Moved existing binary checking code to .githooks/pre-commit.d/02-check-binary. Need to run script/linker.sh in the source directory once for the effect. Added this as an instruction in travis as well.

Adding githooks functionality, adding linker.sh in .travis

---

README.md
src/catalog/catalog_manager.py
src/catalog/df_column.py
src/demo.py
src/parser/insert_statement.py
src/parser/parser_visitor.py
src/spark/session.py
src/utils/logging_manager.py
test/catalog/test_catalog_manager.py
test/loaders/test_frame_loader.py
test/parser/test_parser.py
test/spark/test_session.py

python -m pytest --cov-report= --cov=src/ -s  --log-level=INFO test/parser/test_parser.py

Inherit log level from command line

---

eva.yml
script/test/cleanup.sh
src/executor/plan_executor.py
src/executor/seq_scan_executor.py
src/models/storage/batch.py
test/executor/test_plan_executor.py
test/integration_tests/test_load_executor.py
test/integration_tests/test_select_executor.py
test/integration_tests/test_udf_executor.py
test/util.py

- append ignores index 
- sort returned batch in integration test cases
- Not yield empty batch

Fix problems when batch size is small

---

eva.py
eva.yml
src/executor/plan_executor.py
src/executor/seq_scan_executor.py
src/executor/union_executor.py
src/optimizer/generators/seq_scan_generator.py
src/optimizer/operators.py
src/optimizer/plan_generator.py
src/optimizer/statement_to_opr_convertor.py
src/parser/evaql/evaql_lexer.g4
src/parser/evaql/evaql_parser.g4
src/parser/parser_visitor.py
src/parser/select_statement.py
src/planner/union_plan.py
test/integration_tests/test_select_executor.py
test/integration_tests/test_udf_executor.py
test/optimizer/test_plan_generator.py
test/optimizer/test_statement_to_opr_convertor.py
test/parser/test_parser.py
test/planner/test_plan.py
test/util.py

1. Currently, only UNION ALL is supported, no deduplication. 
2. Fix a bug in DummyObjectDetector, so under any batch size, it can return the correct label.

Add support for UNION operator

---

src/parser/evaql/evaql_parser.g4
src/parser/parser_visitor.py

fix antlr4 error

---

eva.yml
script/test/cleanup.sh
src/udfs/abstract_udfs.py
src/udfs/fastrcnn_object_detector.py
src/udfs/pytorch_abstract_udf.py
test/integration_tests/test_pytorch.py

Add a new integration test cases for data/ua_detrac.mp4 and src/udfs/fastrcnn_object_detector.py.
Tested on Ada-01 with GPU. 
Add gpu_batch_size in eva.yml

pytorch and fastrcnn

---

src/udfs/ssd_object_detector.py
test/integration_tests/test_pytorch.py

* Add another UDF model SSD.
* Hacky way to rewrite pre-processing method in the model.

SSD object detector

---

src/README.md

I just want to doc the high-level workflow here.

High-level system workflow

---

.circleci/config.yml
.coveralls.yml
script/install/before_install.sh
script/install/conda_eva_environment.yml
script/install/install.sh

* Migrate to circle ci.
* Use python-coveralls to publish coverage report.
* Installation instructions carries over user config.

Bring in Circle CI 

---

src/server/db_api.py
test/server/test_db_api.py
test/udfs/ndarray_udfs/test_unnest.py

Raise error if concurrent queries #162
Disallow multiple queries

Enhance db APIs - Raise error if concurrent queries #162

---

README.md

Reverts georgia-tech-db/eva#187

Revert "For Sigmod - revert later"

---

script/test/test.sh

1) removal of __init__.py was required to run the test script. Fixing that.
2) Adding coverage details

Modifying test.sh

---

eva/binder/statement_binder.py
test/binder/test_statement_binder.py
test/binder/test_statement_binder_python37.py

Patch to fix binder for python 3.7

python 3.7 patch

---

eva/utils/generic_utils.py
pytest.ini
script/test/test.sh
setup.py
test/integration_tests/test_mat_executor.py
test/integration_tests/test_pytorch.py
test/integration_tests/test_select_executor.py
test/utils/test_generic_utils.py

-- Need to figure out what tests can be executed without torch
-- Add markers in pytest to run those tests without these dependencies to ensure that the package works fine

Make torch dependencies optional

---

README.md
api-docs/source/contribute/index.rst

Remove redundant documentation link.
Update nonexistent contribution link.
Add instructions to troubleshoot PermissionDenied exceptions.

Clarify contribution instructions in README

---

eva/udfs/ndarray_udfs/crop.py
eva/udfs/udf_bootstrap_queries.py
test/udfs/ndarray_udfs/test_crop.py

Add UDF for cropping frame

---

eva/planner/abstract_plan.py
eva/server/command_handler.py
eva/server/interpreter.py
eva/utils/timer.py
script/test/test.sh
test/server/test_interpreter.py

-- Added a basic timer
-- Need to check timing measurements

feat: Profile queries

---

CHANGELOG.md

* PR #323: Fix EVA Configuration
* PR #321: CI: Caching dependencies
* PR #315: Unified load 
* PR #313: Logo update
* PR #309: UNNEST operator
* PR #307: Feature extractor UDF
* PR #303: Face detector and OCR extractor UDFs
Thanks to @gaurav274, @jarulraj, @xzdandy, @LordDarkula, @eloyekunle, and @devshreebharatia for contributions!

[RELEASE]: v0.0.7

---

setup.py

Refer https://github.com/uber/petastorm/issues/692

petastorm version update to support python 3.9

---

eva/configuration/bootstrap_environment.py
eva/configuration/config_utils.py
test/configuration/test_bootstrap_environment.py

Test `bootstrap_environment()` with temporary directories

Add test for environment setup

---

eva/udfs/pytorch_abstract_udf.py

EVA will feed a pandas dataframe into a UDF so that case must be
addressed

Implement __call__ for pytorch transforms

---

eva/binder/binder_utils.py
eva/catalog/catalog_manager.py
eva/parser/parser_visitor/_create_statements.py
eva/parser/types.py
test/integration_tests/test_load_executor.py
test/parser/test_parser.py
test/util.py

- Added support for NOT NULL 
- Added testcases for partial LOAD (LOAD only some columns for a CSV)

Support for NOT NULL

---

api-docs/_static/custom.css
api-docs/index.rst

Adding the top bar icons and removing custom css for `cards`.

Adding top bar, fixing dark mode

---

.coveragerc
eva/binder/binder_utils.py
eva/executor/load_video_executor.py
eva/storage/opencv_storage_engine.py
eva/udfs/feature_extractor.py
test/__init__.py
test/binder/test_binder_utils.py
test/executor/test_load_executor.py
test/executor/test_upload_executor.py
test/integration_tests/test_drop_executor.py
test/integration_tests/test_load_executor.py
test/integration_tests/test_select_executor.py
test/integration_tests/test_udf_executor.py
test/integration_tests/test_upload_executor.py
test/storage/test_petastorm_storage_engine.py
test/storage/test_video_storage.py
test/util.py

Add dataset support through storage engine, and leave the other parts of the system untouched.

Dataset support 

---

api-docs/_toc.yml

docs: Update _toc.yml

---

tutorials/apps/mnist/eva_mnist_udf.py

Updating `eva_mnist_udf` to new version.

eva_mnist_udf updated

---

api-docs/source/contribute/index.rst

Make it consistent with README

Change name of virtualenv in api-docs to test_eva_db

---

Jenkinsfile
docker/eva_jenkins.Dockerfile

Re-enabling Jenkins test and adding version information in docker setup commands.

chore: re-enable jenkins ci tests

---

.gitattributes

ref: https://github.com/pytorch/vision/issues/2771

fix: Create .gitattributes to ignore notebooks

---

.circleci/config.yml
CHANGELOG.md
eva/version.py
setup.py

* PR #424: Jenkins CI
* PR #432: Emotion palette notebook
* PR #419: Updated Dockerfile
* PR #407: Movie analysis notebook
* PR #404: feat: Lateral join + sampling
* PR #393: feat: EVA config updates
Thanks to @gaurav274, @xzdandy, @LordDarkula, @jarulraj, @Anirudh58, @Aryan-Rajoria for contributions!

[RELEASE]: v0.0.12

---

Jenkinsfile
setup.py

Jenkins should use a dev install and not a regular install of EVA setup. The regular install doesn't install experimental packages.

fix: Jenkins should use dev install

---

.circleci/config.yml
Jenkinsfile

This PR adds a call for a coveralls coverage check from Jenkins CI job
Successful Jenkins job which triggered a coveralls check: https://ada-00.cc.gatech.edu/jenkins/job/kravicha3%20-%20Test%20Jenkins%20CI%20EVA/41/
The coverage check it triggered: https://coveralls.io/jobs/108807569

chore: Add coveralls check trigger in Jenkins CI

---

eva/planner/groupby_plan.py

Hot fix for compatibility with Explain command

Add groupby __str__ for explain

---

.circleci/config.yml
.gitignore
CHANGELOG.md
eva/server/interpreter.py
eva/version.py
script/test/package.sh
setup.py

* PR #498: docs: more details
* PR #495: docs: improve read-the-docs 
* PR #488: docs: fix notebooks
* PR #486: docs: update notebooks + banner
* PR #476: feat: GPU jenkins support

Release v0.1.1

---

CHANGELOG.md
eva/version.py

* PR #506: Added support for windows and macos
* PR #492: Moved to a lark-based parser
* PR #536: Lateral function call to linear data flow
* PR #535: Similarity UDF
* PR #544: fix: catalog improved file and function names
* PR #543: fix: server relaunch does not load metadata tables

[RELEASE]: v0.1.3

---

README.md
docs/source/reference/evaql.rst
docs/source/reference/evaql/select.rst
docs/source/reference/evaql/udf.rst
eva/udfs/ndarray/array_count.py
eva/udfs/udf_bootstrap_queries.py
test/integration_tests/test_array_count.py
test/integration_tests/test_show_info_executor.py
test/udfs/ndarray/test_array_count.py

- `ArrayCount` matches Python naming convention
- This change should not be polluting the UDF registration PR

Rename Array_Count to ArrayCount

---

eva/executor/delete_executor.py
eva/executor/insert_executor.py
eva/expression/expression_utils.py
eva/storage/sqlite_storage_engine.py
test/integration_tests/test_insert_executor.py

Insert feedback

---

CHANGELOG.md
eva/version.py

* PR #623: feat: Adding support for AudioStorageEngine 
* PR #550: feat: support key-value cache for function expressions 
* PR #604: feat: LIKE operator  
* PR #622: feat: sqlalchemy tests 
* PR #618: feat: Predicate UDF Reordering Optimization 
* PR #617: feat: Add UDF Cost Catalog 
* PR #616: feat: Add support for iframe based video sampling 
* PR #606: feat: Add metadata to UDFs in catalog 
* PR #589: feat: Fuzzy Join support in EVA 
* PR #601: feat: Decorators for UDF 
* PR #619: chore: reducing coverage loss 
* PR #595: doc: Adding CatalogManager, INSERT and DELETE documentation 
* PR #605: feat: verify udf consistency by matching the file checksum 
* PR #600: feat: allow UDF's to be created with any name 
* PR #583: feat: Add symlinks to data files instead of copying 
* PR #580: …

[RELEASE]: v0.1.5

---

docs/source/contribute/new_command.rst

doc: fix "extending eva" section

update doc for extending eva

---

eva/parser/eva.lark
eva/parser/lark_visitor/_functions.py
eva/readers/decord_reader.py
eva/storage/video_storage_engine.py
eva/third_party/huggingface/binder.py
eva/third_party/huggingface/create.py
eva/third_party/huggingface/model.py
eva/third_party/huggingface/utils.py
eva/udfs/abstract/hf_abstract_udf.py
script/formatting/formatter.py
test/integration_tests/test_huggingface_udfs.py

feat: Add support for audio based hf models

---

eva/executor/executor_utils.py

fix: typo in executor_utils.py

---

eva/catalog/catalog_manager.py
eva/catalog/models/base_model.py
eva/catalog/sql_config.py

Drop table which are not part of catalog

bug: catalog reset 

---

eva/executor/load_multimedia_executor.py
eva/storage/abstract_media_storage_engine.py
test/benchmark_tests/test_benchmark_pytorch.py
test/integration_tests/test_load_executor.py
test/util.py

* Update file path with hashing
* Not abort if subset of images are corrupted

fix: image loading

---

docs/index.rst

typo: "recogizing" in index.rst

---

docs/_toc.yml
docs/conf.py
docs/requirements.txt

docs: minor updates to read-the-docs

---

CHANGELOG.md
eva/version.py

[RELEASE]: v0.2.4

---

docs/_static/custom.css

docs: style updates

---

README.md
docs/source/reference/evaql/load.rst

docs: Updating Docs based on feedback

---

CHANGELOG.md
eva/version.py
script/releasing/releaser.py

Bump v0.2.7+dev

---

examples/youtube_qa/youtube_qa.py

This PR introduces minor updates to current youtube qa app with new create_udf api and uses EVADBCursor instead of EVADBConnection.

fix: update youtube qa app with new api updates

---

CHANGELOG.md
evadb/version.py
script/releasing/releaser.py

[RELEASE]: 0.2.7

---

CHANGELOG.md
evadb/version.py

[RELEASE]: 0.2.8

---

CHANGELOG.md
evadb/version.py

[RELEASE]: 0.2.9

---

CHANGELOG.md
evadb/version.py

[RELEASE]: 0.2.11

---

test/udfs/test_chatgpt.py

This PR refactors chatgpt test such that it tests with an actual openai api key (as a circleci env variable)

feat: chatgpt test with real API key

---

.circleci/config.yml
setup.py
test/integration_tests/test_create_index_executor.py
test/integration_tests/test_create_table_executor.py
test/integration_tests/test_delete_executor.py
test/markers.py
test/server/test_interpreter.py

ci: Macos build

---

.circleci/config.yml
apps/privategpt/ingest.py
apps/youtube_qa/youtube_qa.py
setup.py
test/app_tests/__init__.py
test/app_tests/test_privategpt.py
test/app_tests/test_youtube_qa.py

test: support for testing apps

---

evadb/binder/binder_utils.py
evadb/binder/statement_binder.py
evadb/binder/statement_binder_context.py
evadb/executor/delete_executor.py
evadb/executor/insert_executor.py
evadb/executor/load_csv_executor.py
evadb/expression/tuple_value_expression.py
evadb/interfaces/relational/db.py
evadb/interfaces/relational/utils.py
evadb/optimizer/optimizer_utils.py
evadb/parser/lark_visitor/_common_clauses_ids.py
evadb/parser/lark_visitor/_create_statements.py
evadb/parser/lark_visitor/_functions.py
evadb/parser/lark_visitor/_table_sources.py
evadb/readers/csv_reader.py
test/binder/test_statement_binder.py
test/binder/test_statement_binder_context.py
test/expression/test_aggregation.py
test/expression/test_expression_tree.py
test/expression/test_expression_utils.py
test/expression/test_logical.py
test/integration_tests/test_load_executor.py
test/parser/test_parser.py
test/readers/test_csv_reader.py

Moved `col_name` -> `name` in `TupleValueExpression` to stay consistent in the codebase.

Code clean up

---

CHANGELOG.md
evadb/version.py

[RELEASE]: 0.2.12

---

CHANGELOG.md
evadb/version.py

[RELEASE]: 0.2.13

---

docs/source/reference/api.rst

docs: minor updates

---

apps/youtube_qa/README.md

this PR improves youtube qa app document based on recent updates.

doc: improve youtube qa app doc

---

setup.py
test/integration_tests/test_ocr_extractor.py

fix: ocr donut model 

---

CHANGELOG.md
evadb/version.py

[RELEASE]: 0.2.14

---

apps/youtube_qa/requirements.txt
evadb/version.py

1. Fix the requirements
2. Reset the version to `dev`

fix: Youtube app

---

CHANGELOG.md
evadb/version.py

[RELEASE]: 0.2.15

---

evadb/udfs/text_filter_keyword.py
test/integration_tests/test_load_executor.py
test/integration_tests/test_load_pdf_executor.py
test/integration_tests/test_text_filtering.py

feat: table filtering based on multiple keywords UDF

---

CHANGELOG.md
evadb/version.py

[RELEASE]: 0.3.0

---

CHANGELOG.md
evadb/version.py

Bump v0.3.1+dev

---

evadb/optimizer/rules/rules.py
evadb/plan_nodes/create_from_select_plan.py
evadb/udfs/chatgpt.py
script/test/test.sh
tutorials/11-similarity-search-for-motif-mining.ipynb

This PR deprecates CREATE MATERIALIZE VIEW query from motif planning notebook

fix: motif_mining query

---

apps/youtube_channel_qa/youtube_channel_qa.py
evadb/interfaces/relational/db.py
evadb/udfs/chatgpt.py
evadb/utils/generic_utils.py
script/test/test.sh
setup.py
test/app_tests/test_pandas_qa.py
test/app_tests/test_youtube_qa.py
test/integration_tests/test_text_filtering.py
test/markers.py
test/server/test_db_api.py
test/udfs/test_chatgpt.py

chore: rename `create_udf` to `create_function`

---

docs/index.rst
docs/source/overview/concepts.rst

docs: updates

---

docs/source/benchmarks/text_summarization.rst

This reverts commit 84efe77618158cf010a80db8af4721b517ac582a.

Revert "Revert "Fix benchmark documentation (#931)""

---

docs/_static/js/top-navigation.js

doc: fix nav bar

---

evadb/executor/create_database_executor.py
test/integration_tests/short/test_create_database_executor.py
test/third_party_tests/test_native_executor.py

* verify connection while creating database
* verbose msg for duplicate database

fix: update more verbose message for creating database

---

evadb/catalog/catalog_utils.py
evadb/third_party/databases/interface.py
evadb/third_party/databases/mysql/__init__.py
evadb/third_party/databases/mysql/mysql_handler.py
evadb/third_party/databases/mysql/requirements.txt
test/third_party_tests/test_native_executor.py
test/unit_tests/storage/test_mysql_native_storage_engine.py
test/unit_tests/storage/test_postgres_native_storage_engine.py

- Integrated mysql data source

msyql integration added

---

docs/source/reference/ai/model-forecasting.rst

- Addressing ` Update documentation with all available parameters.` in #1081.
- Adding documentation for 
* MODEL
* ID
* TIME
* PREDICT
* FREQUENCY

Update parameters documentation for forecast

---

test/integration_tests/long/test_model_forecasting.py

Fix forecasting integration test

---

docs/_static/algolia.css
docs/_static/js/algolia.js
docs/conf.py

This Commit contains necessary css & js file changes and algolia configuration details to add algolia search to eva-db documentation page.

Adding Algolia search to Eva-DB Docs

---

evadb/utils/generic_utils.py

fixes warnings received when using superagi. fixes issue #1127

fix: unclosed file error

---

docs/_toc.yml
docs/source/reference/vector_stores/chromadb.rst
docs/source/reference/vector_stores/faiss.rst
docs/source/reference/vector_stores/index.rst
docs/source/reference/vector_stores/pgvector.rst
docs/source/reference/vector_stores/pinecone.rst
docs/source/reference/vector_stores/qdrant.rst

Added documentation for vector stores including usage examples, dependencies and other requirements.

Documentation on vector stores + vector benchmark

---

evadb/binder/statement_binder.py
evadb/catalog/catalog_manager.py
evadb/catalog/services/column_catalog_service.py
evadb/catalog/services/function_catalog_service.py
evadb/catalog/services/function_io_catalog_service.py
evadb/catalog/services/function_metadata_catalog_service.py
evadb/catalog/services/table_catalog_service.py
evadb/catalog/sql_config.py
test/integration_tests/long/test_create_table_executor.py
test/unit_tests/catalog/test_catalog_manager.py

fix: make the table/function catalog insert operation atomic

---

evadb/binder/function_expression_binder.py
evadb/binder/statement_binder.py
test/unit_tests/binder/test_statement_binder.py

Moved Function Expression Binder to a separate file

refactor: code refactor

---

docs/_toc.yml
docs/source/reference/evaql/set_config.rst
docs/source/reference/evaql/show_config.rst

Resolved #1312 partially, limited to the SQL queries themselves

Added docs for SET and SHOW CONFIG query
