georgia-tech-db/evadb

- src/constants.py
- src/executor/execution_context.py
- src/expression/function_expression.py
- src/udfs/fastrcnn_object_detector.py
- src/udfs/gpu_compatible.py
- src/udfs/pytorch_abstract_udf.py
- src/utils/generic_utils.py
- test/executor/test_execution_context.py
- test/expression/test_function_expression.py
- test/utils/test_generic_utils.py
- Add a mechanism to enable GPU execution
- Implement a Pytorch UDF abstract class that can be used by all Pytorch based UDFs. This UDF abstract class will take care of moving models and Data to GPU.
> Enable GPU execution

- eva.yml
- script/test/cleanup.sh
- src/spark/session.py
- test/integration_tests/test_select_executor.py
- Move all pyspark config to eva.yml
- Add java memory config.
Tested when spark.driver.memory is 4g, batch size 100 works. 
For local testing and travis, keep the default value of spark.driver.memory as 1g, where batch size 50 works.
> Java memory config

- eva.py
- eva.yml
- eva_client.py
- src/models/server/response.py
- src/models/storage/batch.py
- src/server/client.py
- src/server/command_handler.py
- src/server/interpreter.py
- test/models/server/test_response.py
- test/models/storage/test_batch.py
Add client-server support, replace the original pr #102 
Example Usage:
Launch EVA database Server: `python eva.py`
Launch CLI: `python eva_client.py` 
Two queries below will take a while.
`LOAD DATA INFILE 'data/ua_detrac/ua_detrac.mp4' INTO MyVideo;`
`SELECT id, data FROM MyVideo WHERE id < 5;`
> Client server

- src/executor/limit_executor.py
- src/executor/plan_executor.py
- src/optimizer/generators/seq_scan_generator.py
- src/optimizer/operators.py
- src/optimizer/plan_generator.py
- src/optimizer/statement_to_opr_convertor.py
- src/parser/parser_visitor.py
- src/parser/select_statement.py
- src/planner/limit_plan.py
- src/planner/types.py
- test/executor/test_limit_executor.py
- test/integration_tests/test_select_executor.py
- test/optimizer/generators/test_seq_scan_generator.py
- test/optimizer/test_plan_generator.py
- test/optimizer/test_statement_to_opr_convertor.py
- test/parser/test_parser.py
Limit Implementation Steps:
1.  Add parser functionality
- Updated `parser_visitor.py` to process the limit clause (visitor just returns the number in the statement i.e 3 as a `ConstantValueExpression`)
- Updated `select_statement.py` to include limit count
- Test case in `test/parser/test_parser.py`
2. Create a logical plan
- Created a `LogicalLimit` operator in `optimizer/operators.py`
- Call the `LogicalLimit` operator in `optimzer/statement_to_opr_convertor.py` when creating the logical plan
- Test case in `test/optimizer/test_statement_to_opr_convertor.py`
3. Create a physical plan
- Updated `optimizer/plan_generator.py` to consider Limit as a Seq Scan node type
- Created a limit physical plan in `planner/limit_plan.py`. This just receives the information of the limit count from the …
> Limit Implementation

- script/install/conda_eva_environment.yml
Tests fail with pumped up pyspark version (3.1.1).
Failed build: https://app.circleci.com/pipelines/github/georgia-tech-db/eva/63/workflows/6772c302-75e8-49d7-a799-054030414d93/jobs/64
Successful build: https://app.circleci.com/pipelines/github/georgia-tech-db/eva/61/workflows/760c47f8-f793-4308-b063-5decb17e6435/jobs/61
> Freeze pyspark to 3.0.2

- eva.yml
- src/storage/petastorm_storage_engine.py
- test/integration_tests/test_select_executor.py
Use coalesce in pyspark to improve writing speed (#156).
Default value 4. Can be configured in eva.yml.
Issue:
Skip test_select_and_sample in https://github.com/georgia-tech-db/eva/blob/master/test/integration_tests/test_select_executor.py.
Sample needs ORDER BY support.
> coalesce to improve writing speed.

- tutorials/object_detection.ipynb
> Quickstart tutorial 

- eva.yml
- src/executor/disk_based_storage_executor.py
- src/executor/limit_executor.py
- src/executor/load_executor.py
- src/executor/storage_executor.py
- src/optimizer/rules/rules.py
- src/planner/load_data_plan.py
- src/planner/storage_plan.py
- src/readers/abstract_reader.py
- src/readers/petastorm_reader.py
- src/storage/petastorm_storage_engine.py
- test/executor/test_disk_storage_executor.py
- test/executor/test_load_executor.py
- test/executor/test_plan_executor.py
- test/integration_tests/test_load_executor.py
- test/planner/test_plan.py
- test/readers/test_opencv_reader.py
- test/readers/test_petastorm_reader.py
- test/storage/test_petastorm_storage_engine.py
- test/util.py
1. Enabled petastorm caching to speed up data loading.
2. Changed batch_size to batch_mem_size. Rather than using a fixed size batch during execution, Eva infers the batch size based on the video data. The idea is that the number of video frames proceeded together should be configured based on the frame size rather than using a fixed number for all videos.
> Load and Read speed improvement

- eva/executor/create_executor.py
- eva/executor/load_csv_executor.py
- eva/executor/load_executor.py
- eva/executor/load_video_executor.py
- eva/optimizer/operators.py
- eva/optimizer/rules/rules.py
- eva/optimizer/statement_to_opr_convertor.py
- eva/parser/evaql/evaql_lexer.g4
- eva/parser/evaql/evaql_parser.g4
- eva/parser/load_statement.py
- eva/parser/parser_visitor/_load_statement.py
- eva/parser/types.py
- eva/planner/load_data_plan.py
- eva/readers/abstract_reader.py
- eva/readers/csv_reader.py
- test/executor/test_load_executor.py
- test/executor/test_plan_executor.py
- test/integration_tests/test_load_executor.py
- test/optimizer/test_statement_to_opr_convertor.py
- test/parser/test_parser.py
- test/parser/test_parser_visitor.py
- test/planner/test_plan.py
- test/readers/test_csv_reader.py
- test/util.py
Major changes:
1. Support to load CSVs into tables. Split load_executors as load_video_executors and load_csv_executors
2. Added support to specify FORMAT in query
3. Added support to specify columns in LOAD query. 
4. Added/modified all the relevant testcases for this. 
5. Added helper scripts to load datasets.
We can now execute queries like:
`LOAD DATA INFILE 'data/meta.csv' INTO  MyMeta (id, frame_id, video_id, label) WITH FORMAT CSV;`
> Support for loading datasets

- eva/udfs/face_detector.py
- eva/udfs/ocr_extractor.py
- setup.py
- test/integration_tests/test_mat_executor.py
- test/integration_tests/test_pytorch.py
- test/util.py
-- Added UDF and an integration test case
> (feat) Face Detector

- eva/configuration/bootstrap_environment.py
- eva/configuration/configuration_manager.py
- eva/configuration/dictionary.py
- script/test/cleanup.sh
I was getting periodic nondeterministic test failures due to how broken the paths are on system setup.
Use pathlib library for calculating paths when starting eva_server
Building paths by appending strings is error-prone and will not work on other platforms. Python pathlib takes
care of that automatically.
Remove Python reference to python `gettempdir()` in bootstrap_environment
On ada-01, I do not have permission to access `/tmp`, so no matter what I do, the unit tests will fail periodically and need to be fixed. Since eva already creates a `~/.eva/` directory we can use `/.eva/tmp` as a temporary directory and clean it up in the cleanup script.
`EVA_UPLOAD_DIR` in `dictionary.py` was also unused previously which caused confusion.
> Fix EVA Configuration

- api-docs/conf.py
changing `myst-nb` default behaviour of running notebooks before rendering.
> stoping auto execution of jupyter notebooks

- eva/configuration/bootstrap_environment.py
- eva/configuration/config_utils.py
- eva/configuration/configuration_manager.py
- test/configuration/test_configuration_manager.py
`ConfigurationManager` is a singleton that loads the contents of `~/.eva/eva.yml` into memory and uses that to read and write configuration values. The issue with that is if the source file changes, the stale values will continue to be used. This causes confusion if the user wants to change configuration values. When EVA becomes distributed, this system breaks down entirely as different processes will operate with different configuration values.
This PR simply reads directly from `~/.eva/eva.yml` when a read is needed and writes back to the file when `update_value` is called.
> bugfix: Make ConfigurationManager read and update operate on eva.yml

- api-docs/source/contribute/index.rst
The code block with m1 instructions was not rendering correctly
> docs: Fix M1 Mac setup instructions

- eva/executor/sample_executor.py
- test/integration_tests/test_select_executor.py
Reset the index of the data frame after sample.
**Affected query:**
```
SELECT id, label, bbox FROM MyVideo SAMPLE 10 JOIN LATERAL
Unnest(FastRCNNObjectDetector(data)) AS FastRCNN(label, bbox, conf)  WHERE id < 100;
```
**After fix:**
```
Query 1: SELECT id, label, bbox FROM MyVideo SAMPLE 10 JOIN LATERAL
Unnest(FastRCNNObjectDetector(data)) AS FastRCNN(label, bbox, conf)  WHERE id < 100;
Batch Object:
@dataframe:      myvideo.id FastRCNN.label                                 FastRCNN.bbox
0             0         person     [636.2461, 363.62677, 670.9286, 421.6867]
1             0            car   [795.97406, 198.13599, 905.6496, 239.72403]
2             0            car        [926.5628, 108.79296, 960.0, 130.6397]
3             0            car       [835.3279, 232.23067, 960.0, …
```
> Fix lateral join with sample

- eva/udfs/emotion_detector.py
When emotion detector is registered on a machine with no GPU, an error was thrown. This fix avoids the error.
> Avoid error when UDF registered without GPU

- Jenkinsfile
- docker/eva_jenkins.Dockerfile
Earlier, installation of jdk8 was upgraded to jdk11. Looks like petastorm tests, which use pyspark has dependencies in openjdk8. Adding installation of openjdk8 in docker setup to run Jenkins tests.
> fix: petastorm needs pyspark needs openjdk8

- setup.py
Latest release of importlib-metadata (v5.0.0) removes a deprecated endpoint which causes a failure when coveralls tries to lint code.
Ref:
@gaurav274: https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean
> fix: coveralls linting failure

- eva/udfs/abstract/__init__.py
eva_server doesn't run because some modules (particularly "fastrcnn_object_detector.py") import files in the "eva/udfs/abstract/" dir.
"__init__.py" file (in the "eva/udfs/abstract/" directory - where this file resides) is required for python to treat this directory as a package
> fix: importing files in /abstract/ dir

- api-docs/source/overview/installation.rst
Added import statement for defininf `connect` in the [docs](https://evadb.readthedocs.io/en/latest/source/overview/installation.html#connect-to-the-eva-server)
Fixes #515
> Fix variable undefined issue in docs

- eva/executor/orderby_executor.py
- eva/expression/function_expression.py
- eva/udfs/ndarray/open.py
- eva/udfs/ndarray/similarity.py
- eva/udfs/udf_bootstrap_queries.py
- test/integration_tests/test_open.py
- test/integration_tests/test_pytorch.py
- test/integration_tests/test_similarity.py
- test/udfs/ndarray/test_open.py
- test/util.py
Similarity UDF
* Compare distance between feature from open and base feature and return the calculated distance.
> Similarity UDF

- eva/binder/binder_utils.py
- eva/catalog/catalog_manager.py
- eva/catalog/catalog_type.py
- eva/catalog/services/df_service.py
- eva/executor/plan_executor.py
- eva/executor/predicate_executor.py
- eva/executor/seq_scan_executor.py
- eva/executor/show_info_executor.py
- eva/storage/sqlite_storage_engine.py
- setup.py
- test/binder/test_binder_utils.py
- test/integration_tests/test_show_info_executor.py
(1) metadata tables were not being loaded upon server restart, so we implemented reflection to load them; 
(2) the show tables command was not functioning correctly; 
(3) metadata tables have been designated as system tables and can no longer be accessed or modified by user queries.
> fix: server relaunch does not load metadata tables

- test/executor/test_load_executor.py
- test/test_eva_cmd_client.py
Circle CI is failing due to test cases without assertions.
```
FAILED test/test_eva_cmd_client.py::CMDClientTest::test_main - AttributeError: 'called_once_with' is not a valid assertion. Use a spec for the mock if 'called_once_with' is meant to be an attribute.. Did you mean: 'assert_called_once_with'?
FAILED test/executor/test_load_executor.py::LoadExecutorTest::test_should_call_csv_reader_and_storage_engine - AttributeError: 'has_calls' is not a valid assertion. Use a spec for the mock if 'has_calls' is meant to be an attribute.
= 2 failed, 405 passed, 9 skipped, 4 deselected, 38 warnings in 680.68s (0:11:20) =
PYTEST CODE: --|1|-- FAILURE
Exited with code exit status 1
```
> fix: Circle CI error

- eva/binder/statement_binder.py
- eva/catalog/catalog_manager.py
- eva/catalog/catalog_type.py
- eva/catalog/models/index_catalog.py
- eva/catalog/services/index_catalog_service.py
- eva/executor/create_index_executor.py
- eva/optimizer/operators.py
- eva/optimizer/rules/rules.py
- eva/optimizer/statement_to_opr_convertor.py
- eva/parser/create_index_statement.py
- eva/parser/eva.lark
- eva/parser/lark_visitor/_create_statements.py
- eva/plan_nodes/create_index_plan.py
- eva/udfs/udf_bootstrap_queries.py
- test/catalog/services/test_index_catalog_service.py
- test/integration_tests/test_create_index_executor.py
- test/parser/test_parser.py
- test/util.py
* Remove secondary index maintained by ourselves. Instead, we now use `IDMap` provided by the FAISS library, which is also faster in terms of performance.
* Add support of creating index on UDF expression directly. Along with that, add udf signature as part of the index catalog, so the expression can be matched again when index is used later.
> feat: Fix legacy issue in index

- CHANGELOG.md
- eva/udfs/yolo_object_detector.py
- setup.py
Should fix the `models.yolo` not found error found when running debugger on eva.
remove `yolov5-pip` package and instead uses `torch.hub` for yolov5 model.
> fix: debugging issue in yolov5

- eva/binder/statement_binder.py
- eva/executor/create_udf_executor.py
- eva/utils/generic_utils.py
- test/binder/test_statement_binder.py
- test/executor/test_create_udf_executor.py
- test/utils/test_generic_utils.py
Note: Inspired from work on decorators coming in another PR.
We currently enforce that the UDF be named same as the class in the impl file. This seems like an unnecessary restriction. 
This PR introduces the following way of loading the UDF:
- Check if a class with UDF name exists, if yes, loads that.
- If the class with UDF name doesn't exist,
- If the file has a single class load that. 
- Else, raise an error asking user to specify the class name as UDF in case of multiple classes in file. 
Added test cases.
> feat: allow UDF's to be created with any name (irrespective of class name) 

- .gitignore
- setup.py
- test/integration_tests/test_reuse.py
1. Constrained `pandas` to `2.0.0` (breaking changes)
2. Added a windows skip marker to server restart test in `test_reuse`
> fix: updates to restore build

- eva/server/server.py
[server.py](https://github.com/georgia-tech-db/eva/blob/0f4160692b37b6343a5e47d22e3c83aff7a15508/eva/server/server.py#L73) was set to timeout after `60.0` seconds, now changing that to `None`.
It should resolve the error where notebooks randomly fail tests
> fix: Timeout Error

- eva/constants.py
- eva/parser/eva.lark
- eva/readers/decord_reader.py
- test/readers/test_decord_reader.py
This feature allows the users to specify the audio sampling rate like so:
`SELECT UDF(audio,..) FROM VIDEOS SAMPLE AUDIORATE 22500`
If no sampling rate is given, we default to 16000
> feat: Add audio sampling rate

- eva/configuration/bootstrap_environment.py
- eva/configuration/configuration_manager.py
While using pytest-xdist to parallelize tests, config_dir needs to be updated from EVA_DEFAULT_DIR To EVA_DEFAULT_DIR / gw1 (where gw1 is worker_id) always
> test: xdist fix errors due to /.eva directory form a previous run

- eva/expression/function_expression.py
Index is wrong after running some predicates. We should use actual index during iteration. Illustrate using an example
```
col
0    a
1    b
2    c
After running some predicates, two rows may be filtered
col
2    c
```
We may add a test case here.
> fix: cache indices after filtering

- eva/parser/eva.lark
- eva/parser/lark_visitor/_common_clauses_ids.py
- eva/parser/lark_visitor/_create_statements.py
- eva/parser/lark_visitor/_select_statement.py
- eva/parser/lark_visitor/_show_statements.py
- test/parser/test_parser_statements.py
Make grammar keywords case insensitive
> feat: make keywords case insensitive in parser

- eva/configuration/configuration_manager.py
- test/configuration/test_configuration_manager.py
We now safely populate it with a null value.
> fix: stop raising error if category or key missing in config.

- test/integration_tests/test_reuse.py
Reuse testcases fail intermittently. To help debug the issue, I log the contents of batches when the test case fails. #703
> test: add message to help debug an issue

- .circleci/config.yml
- .gitignore
- eva/server/command_handler.py
- script/test/test.sh
- setup.py
- test/integration_tests/test_error_handling_with_ray.py
- test/integration_tests/test_like.py
- test/integration_tests/test_pytorch.py
- test/markers.py
> ci: bump up oldest python version from 3.7 to 3.8

- eva/catalog/models/column_catalog.py
- eva/catalog/models/index_catalog.py
- eva/executor/create_index_executor.py
- test/integration_tests/test_similarity.py
* Foreign key is not correctly configured, which prevents dataset tables to be dropped.
* Storage read gets extra argument after storage engine change.
* Add test case just to make sure index creation and similarity search runs correctly.
> fix: similarity test

- tutorials/00-start-eva-server.ipynb
Currently, eva_server is not restarted when running a tutorial. In this case, if ~/.eva directory is deleted or modified by user, the eva_server process enters a not clean state.
> fix: restart eva_server process for every tutorial

- .git-blame-ignore-revs
Most python files were modified with ebef40e5931de68dabc4f6d25df4b691b1468042. This PR lets us ignore ebef40e5931de68dabc4f6d25df4b691b1468042 while viewing blame.
For more information about the .git-blame-ignore-revs file, see [Ignore Commits in the Blame View](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view).
> refactor: Create .git-blame-ignore-revs 

- .readthedocs.yaml
Build fails on `python 3.7`. Moving docs to `python 3.10` .
Reference: https://docs.readthedocs.io/en/stable/config-file/v2.html
> docs: bump python for docs

- evadb/binder/binder_utils.py
- evadb/binder/statement_binder.py
- evadb/catalog/catalog_utils.py
- evadb/executor/storage_executor.py
- evadb/interfaces/relational/db.py
- evadb/optimizer/operators.py
- evadb/optimizer/rules/rules.py
- evadb/parser/evadb.lark
- evadb/parser/lark_visitor/_expressions.py
- evadb/parser/lark_visitor/_table_sources.py
- evadb/parser/table_ref.py
- evadb/parser/utils.py
- evadb/plan_nodes/storage_plan.py
- evadb/readers/document/document_reader.py
- evadb/readers/document/registry.py
- evadb/storage/document_storage_engine.py
- test/binder/test_statement_binder.py
- test/integration_tests/test_load_executor.py
- test/integration_tests/test_select_executor.py
- test/interfaces/relational/test_relational_api.py
- test/optimizer/test_statement_to_opr_converter.py
- test/util.py
Added support for `chunk_size` and `chunk_overlap` for `document` tables. By default, the values are set to chunk_size=4000, chunk_overlap=200. 
```
SELECT data from docs chunk_size 2000 chunk_overlap 50;
or
cursor.table("docs", chunk_size=2000, chunk_overlap=50).select("data").df()
```
> feat: add chunk_size and chunk_overlap similar to langchain

- evadb/catalog/catalog_type.py
- evadb/catalog/catalog_utils.py
- evadb/readers/document/document_reader.py
- test/integration_tests/test_load_executor.py
Document tables now also project `chunk_id`
Fixed `get_table_primary_columns`:
Set the primary column/s: 
```
TableType.STRUCTURED_DATA: _row_id
TableType.IMAGE_DATA: _row_id
TableType.VIDEO_DATA: _row_id, id
TableType.PDF_DATA: _row_id, paragraph
TableType.DOCUMENT_DATA :  _row_id, chunk_id
```
> fix: minor fix to the catalog utils.

- evadb/executor/execution_context.py
- evadb/optimizer/rules/rules.py
This PR addresses two issues.
1. We previously only allows parallelism when there is more than two GPUs available. I think this is too conservative. First, some functional expressions only run on CPUs and even parallelization of CPU functional expression can bring performance benefit. Additionally, even if there is only one GPU available, it still provide performance benefit when parallelization is enabled because of better GPU utilizations. Currently, I just hardcode the DOP, but I am thinking to allow users to configure this themselves through the `eva.yml`. Any feedback on this? @xzdandy @gaurav274 @jarulraj 
2. I realize a bug related to the previous approach. This will happen for more than 1 GPU case. I will give a concrete example here. Let's assume we have two GPUs. The GPU id that …
> fix: GPU ids and degree of parallelism

- evadb/executor/delete_executor.py
- evadb/optimizer/rules/rules.py
- evadb/third_party/huggingface/model.py
- evadb/udfs/abstract/hf_abstract_udf.py
- test/optimizer/rules/test_batch_mem_size.py
- test/udfs/test_hugging_face.py
1. Pass `batch_mem_size` correctly to storage engines
2. Fix hugging face crash when the number of input token is large then the limit.
👉 Please see our ✅ [Contributing Guide](https://evadb.readthedocs.io/en/stable/source/contribute/index.html) for …
> Fix problems found when running hugging face text summariztion model on large input.

- benchmark/text_summarization/README.md
- benchmark/text_summarization/download_dataset.sh
- benchmark/text_summarization/text_summarization_with_evadb.py
- docs/_toc.yml
- docs/source/benchmarks/text_summarization.rst
> Text summarization benchmark with MindsDB and EvaDB

- evadb/executor/use_executor.py
- evadb/third_party/databases/__init__.py
- evadb/third_party/databases/interface.py
- evadb/third_party/databases/postgres/__init__.py
- evadb/third_party/databases/postgres/postgres.py
- evadb/third_party/databases/postgres/postgres_handler.py
- evadb/third_party/databases/postgres/requirements.txt
- evadb/third_party/databases/types.py
1. Added Abstract Class for database integrations.
2. Implemented postgres integration
> feat: integration for pg_handler added

- apps/youtube_qa/youtube_qa.py
- evadb/udfs/chatgpt.py
This PR modifies YouTube QA app such that it generates more detailed blogs. This is achieved by letting LLM to generate a list of blog sections and make separate chatgpt api calls for each section.
> fix: more detailed YouTube QA app blog generator

- .circleci/config.yml
- setup.py
We simplify the ludwig dependency from `ludwig[full]` to `ludwig[hyperopt,distributed]`.
https://app.circleci.com/pipelines/github/georgia-tech-db/evadb/4910 shows the end to end AutoML training still works as expected.
> Simplify the ludwig dependency

- evadb/interfaces/relational/db.py
- evadb/interfaces/relational/relation.py
- evadb/interfaces/relational/utils.py
- evadb/server/command_handler.py
- evadb/utils/generic_utils.py
- test/integration_tests/long/test_similarity.py
- test/markers.py
* Add some missing qdrant marker and check actual existence of qdrant.
* In-sync with interface.
> fix: use the same interface

- evadb/executor/executor_utils.py
- evadb/models/storage/batch.py
- test/unit_tests/executor/test_seq_scan_executor.py
The original merging has some issues if there is a predicate downstream doing filtering. 
dfa
```
col1
0     1
1     2
```
dfb
```
col2
0     1
1     3
2     2
3     4
```
dfb after filtering
```
col2
0     1
2     2
```
If we do merge of dfa and dfb without resetting the indices, the resulting dataframe will be
```
col1  col2
0   1.0   1.0
1   2.0   1.0
2   2.0   2.0
```
> fix: batch merge causing redundant row

- script/test/test.sh
We enable the unit test and short integration test coverage for open PRs.
> Enable Coverage Check

- docs/_toc.yml
- docs/source/dev-guide/contribute.rst
- docs/source/dev-guide/extend/new-data-source.rst
- docs/source/overview/getting-started/data-source.rst
- docs/source/overview/getting-started/install-guide.rst
- docs/source/reference/api.rst
- docs/source/reference/databases/index.rst
- docs/source/reference/databases/postgres.rst
- docs/source/reference/evaql/create.rst
- docs/source/reference/evaql/load.rst
- docs/source/reference/evaql/select.rst
- docs/source/reference/evaql/use.rst
Inspired by https://ludwig.ai/latest/getting_started/.
Topics will be covered in this PR: 
- Installation Guide
- Integrate Data Source
- USE SQL API
- CREATE DATABASE SQL API
> Revamp getting started. 

- .circleci/config.yml
- script/test/test.sh
* For Postgres CI, add cmd to install packages
* Ignore CI for notebook 14
* It could work with Postgres CI, but we don't have an OpenAI key setup for CI. It still will fail in the end.
> fix: install pkg and ignore tutorials

- docs/_toc.yml
- docs/source/dev-guide/contribute/setup-dev.rst
- docs/source/dev-guide/extend/new-data-source.rst
- docs/source/overview/connect-to-database.rst
- docs/source/overview/getting-started.rst
- docs/source/overview/getting-started/installation-options.rst
- docs/source/reference/databases/mysql.rst
- docs/source/reference/evaql/create.rst
1. Fix link
2. Add mysql into https://evadb.readthedocs.io/en/latest/source/reference/databases/index.html
3. Add documentation requirements in https://evadb.readthedocs.io/en/latest/source/dev-guide/extend/new-data-source.html
> Add mysql as an available data source into documentation

- evadb/models/storage/batch.py
From panda 2.1.0, `pandas.DataFrame.fillna` is deprecated, we should use `pandas.DataFrame.ffill` instead. 
Reference: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html
> `pandas.DataFrame.fillna` is deprecated

- evadb/catalog/sql_config.py
- evadb/executor/create_index_executor.py
- evadb/executor/vector_index_scan_executor.py
- evadb/readers/decord_reader.py
- evadb/readers/document/document_reader.py
- evadb/readers/pdf_reader.py
- evadb/storage/document_storage_engine.py
- evadb/storage/image_storage_engine.py
- evadb/storage/pdf_storage_engine.py
- evadb/storage/sqlite_storage_engine.py
- evadb/storage/video_storage_engine.py
- test/integration_tests/long/test_single_document_similarity.py
- test/unit_tests/readers/test_decord_reader.py
- test/unit_tests/storage/test_sqlite_storage_engine.py
- test/util.py
Use a runtime `row_number` to build the index by incorporating design discussions from https://github.com/georgia-tech-db/evadb/pull/912 and https://github.com/georgia-tech-db/evadb/pull/868.
> fix: create index from single document

- evadb/binder/binder_utils.py
- evadb/binder/statement_binder_context.py
- evadb/storage/native_storage_engine.py
- evadb/third_party/databases/sqlite/sqlite_handler.py
- test/third_party_tests/test_native_executor.py
1. Converting to lowercase for the time being. Changing the binder to take care of case sensitive databases is a long commitment and we can revisit it later.
> fix: evadb is now consistent with lowercase

- docs/source/reference/ai/model-forecasting.rst
- evadb/executor/create_function_executor.py
- evadb/functions/forecast.py
> Fixes date and frequency issues in forecasting

- evadb/binder/statement_binder.py
- evadb/executor/create_function_executor.py
- evadb/utils/generic_utils.py
Lowercasing function_type and target string before matching so as to make it case insensitive
modified:   evadb/binder/statement_binder.py
modified:   evadb/executor/create_function_executor.py
@xzdandy @gaurav274 do we want a test for checking lowercase as well? If so exactly what should it check?
Although #1071 discusses only `Ludwig`, I saw the same behaviour in the case of `HuggingFace` as well and made that case insensitive as well
> Making `Ludwig` and `HuggingFace` case insensitive

- evadb/utils/generic_utils.py
- test/unit_tests/binder/test_statement_binder.py
Fixed #1106 
Handled string NULL cases
modified:   evadb/utils/generic_utils.py
Added a simple test for case insensitive string matching
modified:   test/unit_tests/binder/test_statement_binder.py
@xzdandy let me know if there is a better place for the test I have added. It is pretty simple and straightforward. Let me know if more cases have to added to it.
> Added null handling and tests for case insensitive string matching

- evadb/binder/statement_binder.py
- evadb/executor/create_function_executor.py
- evadb/functions/forecast.py
- test/integration_tests/long/test_model_forecasting.py
- test/unit_tests/binder/test_statement_binder.py
- test/unit_tests/utils/test_generic_utils.py
Current forecast functions only output the y value. This PR fixes the binded output column, so forecasting functions also return unqiue_id and datastamp column.
> Set the right output column type for forecast functions

- test/unit_tests/server/test_interpreter.py
Modification to std in/out causes strange behavior from pytest side.
> fix: flaky ci unit tests

- docs/_toc.yml
- docs/source/usecases/homesale-forecast.rst
- script/test/test.sh
- Add home sale forecast use case into documentation
> Add home sale forecast usecase into documentation

- apps/privategpt/ingest.py
- apps/privategpt/privateGPT.py
- apps/story_qa/evadb_qa.py
- apps/youtube_channel_qa/README.md
- apps/youtube_channel_qa/youtube_channel_qa.py
- apps/youtube_qa/youtube_qa.py
- script/formatting/formatter.py
Update evadb apps
1. Change `udf` to `function`
2. Update queries to `cursor.query("...")`
> Updates evadb apps

- .github/workflows/release.yml
- .github/workflows/sync.yml
- docs/source/dev-guide/release/pypi-account.rst
- docs/source/dev-guide/release/release-steps-old.rst
- docs/source/dev-guide/release/release-steps.rst
Need to figure out a way to test it.
> feat: add github actions to sync and release wheel

- docs/source/overview/model-inference.rst
- docs/source/reference/ai/model-train.rst
- docs/source/reference/evaql/create.rst
- evadb/executor/create_function_executor.py
- evadb/optimizer/operators.py
- evadb/optimizer/rules/rules.py
- evadb/optimizer/statement_to_opr_converter.py
- evadb/parser/create_function_statement.py
- evadb/parser/evadb.lark
- evadb/parser/lark_visitor/_functions.py
- evadb/plan_nodes/create_function_plan.py
- test/integration_tests/long/test_function_executor.py
- test/unit_tests/executor/test_create_udf_executor.py
- test/unit_tests/executor/test_plan_executor.py
- test/unit_tests/optimizer/test_statement_to_opr_converter.py
- test/unit_tests/parser/test_parser.py
- test/unit_tests/plan_nodes/test_plan.py
> `CREATE OR REPLACE FUNCTION`

- evadb/functions/ludwig.py
- evadb/models/storage/batch.py
- evadb/utils/generic_utils.py
We can not reproduce the problem locally, so the first guess is 
1 . Convert dask dataframe to panda dataframe. This works. Check [Colab](https://colab.research.google.com/drive/1omSVrAOQvWmGkdbGSTWyMlQA90n1eWvQ#scrollTo=_7m-QQG5U3_C).
> Fix model train with Ludwig on Colab

- evadb/binder/create_index_statement_binder.py
- evadb/binder/statement_binder.py
- evadb/catalog/catalog_type.py
- evadb/executor/create_index_executor.py
- evadb/executor/vector_index_scan_executor.py
- evadb/optimizer/operators.py
- evadb/optimizer/rules/rules.py
- evadb/parser/evadb.lark
- evadb/parser/lark_visitor/__init__.py
- evadb/parser/lark_visitor/_create_statements.py
- evadb/plan_nodes/abstract_plan.py
- evadb/plan_nodes/vector_index_scan_plan.py
- evadb/third_party/databases/postgres/postgres_handler.py
- test/third_party_tests/test_native_create_index.py
- test/third_party_tests/test_native_similarity_index.py
I will need some feedback on the design here. @xzdandy @gaurav274 
This PR reflects my initial design for in-database index features like pgvector. My initial idea is to offload as much as possible to the native database. When we create an index and do the index scan, we simply push an emulated query to the underlying database. While this is doable, this will introduce separate implementation paths in different components including the optimizer and the executor. 
Other than the current design, another option is to reuse the third-party vector integration interface. There are also a few details that I am not clear about
* For other vector libraries, we keep an index entry in our own catalog. Do we still maintain that even for pgvector? In the original implementation, the index catalog …
> feat: integrate with pgvector

- evadb/utils/generic_utils.py
- test/integration_tests/long/test_similarity.py
- test/markers.py
The integration test currently fails if pinecone is not installed. Added a skip marker for the same.
> Skip pinecone test if pinecone is not installed

- evadb/functions/function_bootstrap_queries.py
- evadb/parser/evadb.lark
- evadb/parser/lark_visitor/_functions.py
- test/integration_tests/short/test_select_executor.py
- test/util.py
> Add support for function calls without input arguments: `FUNC()`

- evadb/binder/statement_binder.py
- evadb/executor/create_function_executor.py
- evadb/functions/sklearn.py
- evadb/utils/generic_utils.py
- test/integration_tests/long/test_model_train.py
Starting this PR for integrating sklearn linear regression for EvaDb.
> Adding support for Sklearn linear regression in EvaDB

- .circleci/config.yml
- evadb/catalog/catalog_type.py
- evadb/executor/executor_utils.py
- evadb/interfaces/relational/db.py
- evadb/parser/evadb.lark
- evadb/parser/lark_visitor/_create_statements.py
- evadb/third_party/vector_stores/chromadb.py
- evadb/third_party/vector_stores/utils.py
- evadb/utils/generic_utils.py
- script/formatting/spelling.txt
- setup.py
- test/integration_tests/long/test_similarity.py
- test/markers.py
Added support for ChromaDB in Eva. Will focus on benchmarking the existing vector stores after this.
> Chroma vector store

- .circleci/config.yml
- evadb/utils/generic_utils.py
- script/test/test.sh
- setup.py
- test/integration_tests/long/test_model_train.py
- test/markers.py
> feat: add testmon in pytest

- .circleci/config.yml
- test/integration_tests/long/test_similarity.py
- test/util.py
> Fix staging CI setup

- evadb/executor/create_executor.py
- evadb/executor/load_csv_executor.py
- evadb/storage/native_storage_engine.py
- test/integration_tests/long/test_similarity.py
1. `CREATE TABLE` returns better response messages. 
2. Skipping `PINECONE` testcase as it is flaky. 
3. Handle the scenario when `CREATE TABLE AS SELECT` fails in the native database table.
> fix: improve messaging and fix bugs

- evadb/binder/binder_utils.py
- evadb/binder/create_index_statement_binder.py
- evadb/binder/statement_binder.py
- evadb/binder/tuple_value_expression_binder.py
- evadb/catalog/catalog_manager.py
- evadb/catalog/models/index_catalog.py
- evadb/catalog/models/utils.py
- evadb/catalog/services/index_catalog_service.py
- evadb/executor/create_index_executor.py
- evadb/optimizer/operators.py
- evadb/optimizer/rules/rules.py
- evadb/optimizer/statement_to_opr_converter.py
- evadb/parser/create_index_statement.py
- evadb/parser/lark_visitor/_create_statements.py
- evadb/plan_nodes/create_index_plan.py
- evadb/third_party/vector_stores/faiss.py
- test/integration_tests/long/test_create_index_executor.py
- test/unit_tests/binder/test_statement_binder.py
- test/unit_tests/optimizer/test_statement_to_opr_converter.py
- test/unit_tests/parser/test_parser.py
The first step to do automatic index updates on insertions. 
Replace the old version of creating an index, which directly reads data from the storage engine. 
It now reads data from the children's plans: SeqScan and Storage.
> feat: create index from projection

- docs/source/reference/evaql/create.rst
- docs/source/shared/postgresql.rst
- evadb/parser/lark_visitor/_create_statements.py
- test/unit_tests/parser/test_parser.py
Users can now create a table with just `FLOAT` without providing the dimensions.
Earlier:
```sql
CREATE TABLE ETTM1 (
date TEXT(30),
hufl FLOAT(5,7),
hull FLOAT(5,7),
mufl FLOAT(5,7),
mull FLOAT(5,7),
lufl FLOAT(5,7),
lull FLOAT(5,7),
ot FLOAT(5,7));
```
Now:
```sql
CREATE TABLE ETTM1 (
date TEXT,
hufl FLOAT,
hull FLOAT,
mufl FLOAT,
mull FLOAT,
lufl FLOAT,
lull FLOAT,
ot FLOAT);
```
Fixes #1260.
> Remove dimensions from `TEXT` and `FLOAT`

- evadb/binder/statement_binder_context.py
- test/integration_tests/short/test_select_executor.py
- test/unit_tests/binder/test_statement_binder_context.py
Below is the example error message:
```
evadb.binder.binder_utils.BinderError: Cannnot find column name2. Did you mean name? The available columns are ['avatar_url', 'bio', 'blog', 'collaborators', 'company', 'contributions', 'disk_usage', 'email', 'events_url', 'followers', 'followers_url', 'following', 'following_url', 'gists_url', 'gravatar_id', 'hireable', 'html_url', 'id', 'invitation_teams_url', 'location', 'login', 'name', 'node_id', 'organizations_url', 'owned_private_repos', 'private_gists', 'public_gists', 'public_repos', 'received_events_url', 'repos_url', 'role', 'site_admin', 'starred_url', 'subscriptions_url', 'team_count', 'total_private_repos', 'twitter_username', 'type', 'url'].
```
**Limitation**: To keep the output clean, we only do fuzzy match on the columns and skip …
> Improve the error message when there is a typo in the column name in the query. 

- benchmark/text_summarization/text_summarization_with_evadb.py
text_summarization uses drop udf instead of drop function.
> fix: text_summarization uses drop udf

- evadb/catalog/models/function_metadata_catalog.py
- evadb/parser/evadb.lark
- evadb/parser/lark_visitor/_expressions.py
- test/integration_tests/long/test_function_executor.py
> feat: function_metadata supports boolean and float 

- evadb/catalog/catalog_manager.py
- evadb/executor/show_info_executor.py
- evadb/parser/evadb.lark
- evadb/parser/lark_visitor/_show_statements.py
- evadb/parser/show_statement.py
- evadb/parser/types.py
- evadb/plan_nodes/show_info_plan.py
- test/integration_tests/short/test_show_info_executor.py
- test/unit_tests/parser/test_parser_statements.py
> feat: add support for show databases

- docs/source/overview/connect-to-data-sources.rst
- docs/source/reference/databases/sqlite.rst
- docs/source/reference/evaql.rst
- docs/source/usecases/classification.rst
- docs/source/usecases/forecasting.rst
- docs/source/usecases/sentiment-analysis.rst
I have seen students getting confused with the documentation wherein they try to always create a connection to some database (Eg : Postgres) before trying to insert or query data. Adding a note in the documentation to help clear this point up as well as describe that Eva has native storage support for SQLite.
> Add documentation note for connecting to existing SQL DB

- evadb/executor/vector_index_scan_executor.py
Profiling on Vector Scan showed that we are spending a lot of time in the post-processing logic doing a Nested Join. This is an initial commit to change that into a Join using Pandas. Change showed ~50% improvement in Similarity Queries.
> Convert nested join in Vector Queries to Pandas Merge. 

- evadb/functions/function_bootstrap_queries.py
- evadb/functions/helpers/concat.py
- evadb/functions/helpers/lower.py
- evadb/functions/helpers/upper.py
- test/integration_tests/long/functions/helpers/test_str_helper_functions.py
Added some string helper functions that were missing based on student feedback. This PR adds support for UPPER, LOWER and CONCAT.
Queries of the form are now supported:
`SELECT CONCAT(UPPER(col1), LOWER(col2), "SOME_SUFFIX") FROM TABLE1`
> String Helper functions in EvaDB

- evadb/binder/function_expression_binder.py
- evadb/executor/create_function_executor.py
- test/integration_tests/long/test_model_train.py
- test/integration_tests/short/test_select_executor.py
Let us show the validation score and training time for the XGBoost AutoML model trained. This shall give us fair enough idea on how the model trained on the training data set.
> Add the validation score and training time for create_function in XGBoost

- .gitignore
The environment created in the setup instructions in the documentation calls the environment `test_eva_db`
> Add test_eva_db to gitignore

- docker/Dockerfile
Update the DockerFile in order to resolve dependency issues along with fixing the invalid CMD that was previously passed in.
> Fix #1333 dependency and CMD in DockerFile

- evadb/executor/insert_executor.py
- evadb/executor/vector_index_scan_executor.py
- test/integration_tests/long/test_similarity.py
This PR fixes an issue in CREATE INDEX IF NOT EXISTS command wherein if 'IF NOT EXISTS' is passed, we had an unreferenced variable issue. Added Unit Tests to check the correctness of both the cases. 
Also reverted the index changes while merging dataframes after vector scan, as it's failing for some cases where indexes can be undefined.
> CREATE INDEX IF NOT EXISTS is broken.

- evadb/parser/evadb.lark
- test/unit_tests/parser/test_parser.py
Support semi-colons in string literals for queries of the form:
```
"""SELECT ChatGPT("Here's a; question", "This is the context") FROM TAIPAI;"""
```
Also support string escape to run ChatGPT queries more easily:
```
"""SELECT ChatGPT('Here\\'s a question', 'This is the context') FROM TAIPAI;"""
```
> Support semicolon and escaped strings in lark

- evadb/binder/function_expression_binder.py
- evadb/utils/generic_utils.py
- test/integration_tests/short/test_generic_utils.py
- test/integration_tests/short/test_select_executor.py
Added separate error handling for ModuleNotFoundError and FileNotFoundError
modified:   evadb/utils/generic_utils.py
> [WIP] Improving error handling messages for Custom Functions

- evadb/executor/load_multimedia_executor.py
- test/integration_tests/long/test_load_executor.py
Issue - [721](https://github.com/georgia-tech-db/evadb/issues/721)
Currently, we abort the entire process when the load executor encounters a corrupted file.
> logging an error message for invalid files while loading

- docs/_toc.yml
- docs/source/reference/evaql/load_pdf.rst
Issue #1067 about not being able to load pdf files, was verified to be working with evadb documentation pdf and a new page for loading pdf is added to the documentation.
> Verified that issue #1067 is resolved and added documentation for load pdf functionality.

- docs/source/overview/concepts.rst
- docs/source/reference/ai/model-forecasting.rst
- docs/source/reference/databases/github.rst
- evadb/executor/create_function_executor.py
In the previous commit, we added the changes for displaying the train scores and train times for XGBoost. We plan to add similar changes to Ludwig integration as well.
> Add train scores for ludwig in the create function handler.

- evadb/functions/chatgpt.py
- evadb/functions/dalle.py
- setup.py
- test/integration_tests/long/functions/test_chatgpt.py
- test/unit_tests/test_dalle.py
Migrate ChatGPT function to openai v1.0.
The test is skipped in circleCI because we must supply the `OPENAI_API_KEY`. The test passes on local machine.
> Migrate ChatGPT function to openai v1.0
